---
title: "R_maps_practice"
format: html
editor: visual
---

```{r}
knitr::opts_knit$set(root.dir = "C:/GerseyNotSLU/Datahandlingcourse/")
#install.packages("install.load")
install.load::install_load("dplyr", "raster", "sf", "tidyverse", "maps", "terra", "ggspatial", "mapview")
knitr::opts_chunk$set(warning = TRUE, # show warnings
                      message = TRUE, # show messages
                      error = TRUE, # do not interrupt generation in case of errors,
                      echo = TRUE)

# Load packages
pcks <- list("dplyr", 
             "sf",        # used for handling spatial data 
             "ggspatial", # spatial for ggplot2 
             "raster",    # used for raster data 
             "terra",     # used for raster data
             "mapview",   # interactive maps 
             "tidyverse")

sapply(pcks, require, char = TRUE) 

```

You can add options to executable code like this

```{r}
#| echo: false
2 * 2
```

The `echo: false` option disables the printing of code (only output is displayed).
