---
title: "Practice_ggplot1"
format: html
editor: visual
---

Penguin exercise

```{r}

require(ggplot2)
library(ggplot2)
data("penguins")

p <- ggplot(data = penguins)
p + geom_point(aes(x=flipper_len,y=body_mass, colour = species))


```

```{r}
setwd("C:/GerseyNotSLU/Datahandlingcourse/")
gapminder <- read.csv("https://raw.githubusercontent.com/swcarpentry/r-novice-gapminder/main/episodes/data/gapminder_data.csv")
gapminder <- as_tibble(gapminder) # make it tibble or tbl data type too
library("ggplot2")
ggplot(data = gapminder) #blank graph
ggplot(data = gapminder, mapping = aes(x = gdpPercap, y = lifeExp)) #no geom added yet
ggplot(data = gapminder, mapping = aes(x = gdpPercap, y = lifeExp)) +
  geom_point()

ggplot(data = gapminder, mapping = aes(x=year, y=lifeExp, color=continent)) +
  geom_line()

ggplot(data = gapminder, mapping = aes(x=year, y=lifeExp, group=country, color=continent)) +
  geom_line()

ggplot(data = gapminder, mapping = aes(x=year, y=lifeExp, group=country, color=continent)) +
  geom_line() + geom_point() #can mix points and lines

ggplot(data = gapminder, mapping = aes(x=year, y=lifeExp, group=country)) +
  geom_line(mapping = aes(color=continent)) + geom_point()

ggplot(data = gapminder, mapping = aes(x=year, y=lifeExp, group=country)) +
  geom_line(color="blue") + geom_point() #if you want to change it all to one color you don't add it to the aes

ggplot(data = gapminder, mapping = aes(x=year, y=lifeExp, group=country)) + geom_point() + geom_line(mapping = aes(color=continent))

```

Transformations and stats

```{r}
ggplot(data = gapminder, mapping = aes(x = gdpPercap, y = lifeExp)) +
  geom_point(alpha = 0.5) + scale_x_log10() 
#The scale_x_log10 function applied a transformation to the coordinate system of the plot, so that each multiple of 10 is evenly spaced from left to right. For example, a GDP per capita of 1,000 is the same horizontal distance away from a value of 10,000 as the 10,000 value is from 100,000. This helps to visualize the spread of the data along the x-axis.

ggplot(data = gapminder, mapping = aes(x = gdpPercap, y = lifeExp)) +
  geom_point(alpha = 0.5) + scale_x_log10() + geom_smooth(method="lm")
ggplot(data = gapminder, mapping = aes(x = gdpPercap, y = lifeExp)) +
  geom_point(alpha = 0.5) + scale_x_log10() + geom_smooth(method="lm", linewidth=1.5)
ggplot(data = gapminder, mapping = aes(x = gdpPercap, y = lifeExp)) +
  geom_point(mapping = aes(color=continent), size = 3, alpha = 0.3) + scale_x_log10() + geom_smooth(method="lm", linewidth=1.5) #modified size, transparency and colors of points
ggplot(data = gapminder, mapping = aes(x = gdpPercap, y = lifeExp, color=continent)) + 
  geom_point(mapping = aes(shape = continent), size = 3, alpha = 0.5) + 
  scale_x_log10() + geom_smooth(method="lm", linewidth=1)


```

Making mult-panel figures

```{r}
americas <- gapminder[gapminder$continent == "Americas",] #create a subset
ggplot(data = americas, mapping = aes(x = year, y = lifeExp)) +
  geom_line() +
  facet_wrap( ~ country) +
  theme(axis.text.x = element_text(angle = 45)) #rotate the x-axis slightly
#add text and fix things up
lifeExp_plot <- ggplot(data = americas, mapping = aes(x = year, y = lifeExp, color=continent)) +
  geom_line() + 
  facet_wrap( ~ country) +
  labs(
    x = "Year",              # x axis title
    y = "Life expectancy",   # y axis title
    title = "Figure 1",      # main title of figure
    color = "Continent"      # title of legend
  ) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

print(lifeExp_plot)

ggsave(filename = "results/lifeExp_Americas.png", plot = lifeExp_plot, width = 15, height = 15, dpi = 300, units = "cm")

```

Boxplot

```{r}
ggplot(data = gapminder) + geom_violin(aes(x = as.factor(year), y = lifeExp)) #can see the difference between years
ggplot(data = gapminder) + geom_boxplot(aes(x = as.factor(year), y = lifeExp, fill = continent)) + facet_grid(~continent) #can see the difference between continents and years
ggplot(data = gapminder) + geom_boxplot(aes(x = as.factor(year), y = lifeExp, fill = continent)) +
  labs(
    x = "Year",              # x axis title
    y = "Life expectancy",   # y axis title
    title = "Figure 2",      # main title of figure
    fill = "Continent"      # title of legend
  ) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

library(RColorBrewer)

p <- ggplot(data = gapminder, mapping = aes(x = continent, y = lifeExp, fill = continent)) +
 geom_boxplot() + facet_wrap(~year) +
 ylab("Life Expectancy") +
  labs(
    title = "Figure 2. Life expectancy across continents and years",
    fill ="Continent") +
  theme(axis.title.x = element_blank(),
       axis.text.x = element_blank(),
       axis.ticks.x = element_blank()) 

p + scale_fill_brewer(palette = "Greys")

ggsave(filename = "results/lifeExp_facet_years.png", width = 15, height = 15, dpi = 300, units = "cm")


```
